[env]
NAME = "{{project-name}}"
PROJECT = "${PWD}/${NAME}.uproject"

[tasks.install]
command = "adb"
args = ["install", "-r", "-d", "Binaries/Android/${NAME}-arm64.apk"]

[tasks.clean]
command = "rm"
args = ["-r", "Binaries", "Build", "DerivedDataCache", "Intermediate", "Saved", "Plugins", "Script"] 

[tasks.recover]
script = '''
mv *.uproject \{\{project-name\}\}.uproject
'''
